# Generated by Django 3.1 on 2020-08-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200810_1000'),
        ('comments', '0005_auto_20200810_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_email', to=settings.AUTH_USER_MODEL, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_name', to=settings.AUTH_USER_MODEL, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_post', to='blog.post', verbose_name='文章'),
        ),
    ]
