# Generated by Django 3.1 on 2020-08-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo_number',
            new_name='phone_number',
        ),
    ]
